spring:
  datasource:
    url: ${SUPERFERCHO_DB_URL:jdbc:postgresql://localhost:5432/superfercho}
    username: ${SUPERFERCHO_DB_USERNAME:superfercho}
    password: ${SUPERFERCHO_DB_PASSWORD:superfercho}
